- pipeline.id: tables
  path.config: "/usr/share/logstash/pipeline/logstash-tables.conf"
- pipeline.id: columns
  path.config: "/usr/share/logstash/pipeline/logstash-columns.conf"
- pipeline.id: lints
  path.config: "/usr/share/logstash/pipeline/logstash-lints.conf"